### ISSUE TITLE
XMP missing

### ISSUE THREAD

**Issue by florian-senn** [MikeKovarik/exifr#13]
Hey there!

Thanks for your great work, out of all Exif-parsers for NodeJS yours works best.

Unluckily, I've got some issues reading XMP of my Mavic 2 Drone Footage. When I use your page (https://exifr.netlify.com/), it works like a charm and XMP-APP1 output is shown, but when I try it in NodeJS on my project, it'll fail with the same picture as input. Any clues?

    function parseAsync (source) {
      return new Promise(
        function (resolve, reject) {
          parse(source, { xmp: true, gps: true, mergeOutput: false, exif: false })
            .then(
              result => {
                console.log(result)
                resolve({ latitude: result.gps.latitude, longitude: result.gps.longitude, altitude: result.gps.GPSAltitude }
                )
              })
            .catch()
        }
      )
    }

![2019-10-16](https://user-images.githubusercontent.com/14863213/66918634-14cb5380-f020-11e9-86b4-d4b7cbc781cd.png)

Best regards

Florian

**Comment by florian-senn** [comment]
Got some xmp-output after I disabled postProcess, but the result seems quite spaghetti and still not the same result as on your page.
![2019-10-16 (1)](https://user-images.githubusercontent.com/14863213/66919382-86f06800-f021-11e9-97d0-61f1e69e027e.png)

**Comment by MikeKovarik** [comment]
Hello. First of all sorry for responding so late. I am just returning from a vacation and it will still take some time to get home from airport, and get back to daily life before I can address this further.

I think I know what is going on. On frontend the library tries to parse as little bytes as possible and assumes it is located somewhere within the first 64 kb of the file. Otherwise exifr assumes the image doesn't contain exif (or xmp in your case) and just stops fetching and looking whereas the Nodejs version can very quickly access the disk so it keeps reading further blocks as needed.

You can either change the amount of bytes to read or fetch the whole file and feed Uint8Array or ArrayBuffer to the library.

Also could you post your image? I will write test for it.

Sidenote: I am currently (past month or so) doing a rewrite to make the code more modular and configurable to make it even better to prevent problems like this.

That's it from me from the phone for now. Thank you for using the library. Glad you like it.

**Comment by florian-senn** [comment]
Hi Mike, no problem! I'm glad you provide a library for EXIF!

I tried to read the whole image, but didn't work either.

I wrote my own solution for specificly parsing DJI XMP. By the way, on your demo site I can see the files' XMP data, only when I use it myself as NPM package it doesn't work.

Can't upload stuff to github right now, so I can only provide you the test image from my repo:
[Test JPG](https://github.com/florian-senn/dji-XMetaParser/tree/master/test)

**Comment by florian-senn** [comment]
Ok, here we go, finally I could upload everything:
![test1](https://user-images.githubusercontent.com/14863213/67376757-f536ac80-f584-11e9-9877-d354f92aed29.jpg)
![FireShot Capture 045 - Exifr - exifr netlify com](https://user-images.githubusercontent.com/14863213/67376824-0d0e3080-f585-11e9-91f3-15a6b8abbba6.png)

**Comment by MikeKovarik** [comment]
Hello. I just wanted to let you know that I am actively working on this issue. I'm doing a major rewrite of the library in branch [next-major-rewrite](https://github.com/MikeKovarik/exifr/tree/next-major-rewrite) and I included this image in tests and will make sure that it works.

There's still lot of work to be done. I hope it will get released by the end of this month.

**Comment by florian-senn** [comment]
@MikeKovarik thanks for your work! Just let me know if I can help you!

**Comment by MikeKovarik** [comment]
Happy to announce that 3.0.0 is about to be released and fixes this problem
