### ISSUE TITLE
Specifying what to parse is not working as expected

### ISSUE THREAD

**Issue by FrancoAucamp** [MikeKovarik/exifr#17]
exifr.parse(file, ['Model', 'FNumber', ...]) still returns the full exif object in react

**Comment by MikeKovarik** [comment]
Hello. Yes :D sorry for the misunderstading. This is the syntax for version 3.0.0. I've been developing it on separate branch and just merged it to master a couple of days ago. But 3 isn't yet publish because I found a few more things to polish. I'm very close to publishing. I think tomorrow because I still want to investigate #12 later today.

For now you can clone this repo, or just comment the `['Model', 'FNumber', ...]` and just use `exifr.parse(file)` because it will work when you upgrade to v3.

thank you

**Comment by FrancoAucamp** [comment]
Hi 

Cool, no problem thanks for the quick reply. Great library BTW😊

Now that I have your attention… I know request are a pain in the ass but…

It would be great if you can consider parsing HEIF also for the new iphones. That is the only thing I’m missing in this great library!

 

Regards,

 

Franco

**Comment by MikeKovarik** [comment]
No problem, I'm glad you use it. And I'm actually happy that there's someone using it and wanting to improve it.

Actually HEIC (or HEIF, afaik there's many names for the same thing) support is already done in this v3. There's a [src/file-parsers/heic.js](https://github.com/MikeKovarik/exifr/blob/master/src/file-parsers/heic.js) for that. And you can try it out right now by going to [mutiny.cz/exifr/](https://mutiny.cz/exifr/). It's hosted directly from github's master so it already runs v3 with HEIC. You can just drag and drop your files there to see if it works. Or let me know and send the photos that don't. I would write fix around them and add write tests for them.

![image](https://user-images.githubusercontent.com/3995401/74732861-693f4380-524b-11ea-90c0-f2053ba03b2e.png)
