### ISSUE TITLE
React (library?) compatibility / rollup

### ISSUE THREAD

**Issue by viters** [MikeKovarik/exifr#22]
Described in https://github.com/MikeKovarik/exifr/issues/22#issuecomment-598206352

**Comment by MikeKovarik** [comment]
Hello, thank you for the feedback. I appreciate it because I haven't used react in a while so this flew under my radar.

However I couldn't replicate your problem.

I don't know `react-scripts` so I went to the react-script's [npm](https://www.npmjs.com/package/react-scripts) which lead me to [Getting started at create-react-app.dev](https://create-react-app.dev/docs/getting-started/)

From there i did
```
npx create-react-app my-app
cd my-app
npm start
```

then i installed exifr, added it to App.js but it runs without problems.

No error in terminal, with typescript, nor in the browser.

![image](https://user-images.githubusercontent.com/3995401/76528223-c015f280-6470-11ea-85fd-79793b463893.png)

Could you please tell me more about your setup? Or better yet, make a minimal repo where the problem is reproducible?

Thank you.

**Comment by viters** [comment]
Sorry, it looks like I was too quick in my assumptions.

I have a library that I maintain and use it in react apps. I've tried to use `exifr` in this library. When I build library, everything is fine - but later when I build react app that uses my library I receive

```
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

My library tsconfig:
```json
{
  "compilerOptions": {
    "outDir": "dist",
    "target": "es5",
    "moduleResolution": "node",
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "removeComments": true,
    "esModuleInterop": true,
    "jsx": "react",
    "allowSyntheticDefaultImports": true,
    "skipLibCheck": true
  },
  "include": ["src/"]
}
```

And rollup script:
```js
import typescript from 'rollup-plugin-typescript2';
import commonjs from 'rollup-plugin-commonjs';
import external from 'rollup-plugin-peer-deps-external';
import resolve from '@rollup/plugin-node-resolve';

import pkg from './package.json';

export default {
  input: 'src/index.ts',
  output: [
    {
      file: pkg.main,
      format: 'cjs',
      exports: 'named',
      sourcemap: true,
    },
    {
      file: pkg.module,
      format: 'es',
      exports: 'named',
      sourcemap: true,
    },
  ],
  plugins: [
    external(),
    resolve({
      browser: true,
    }),
    typescript(),
    commonjs({
      include: ['node_modules/**'],
      exclude: ['**/*.stories.js', 'test/'],
      namedExports: {
        'node_modules/react/react.js': ['Children', 'Component', 'PropTypes', 'createElement'],
        'node_modules/react-dom/index.js': ['render'],
      },
    }),
  ],
};
```

I did not have such issues with other libraries up till now.

**Comment by MikeKovarik** [comment]
Hello. 

No don't worry. I'm surprised this problem happened at all. And I'm glad you gave me some info on how to replicate it since I absolutely want to fix it. And of course I would love exifr to be your replacement for exif.-s :)

I managed to replicate the problem and then track it down back to webpack.

I tried fixing it and it seems that it works. Try the new 4.3.2 version. I hope it works.

If not, please reopen the issue.
