### ISSUE TITLE
Replace exif js

### ISSUE THREAD

**Issue by Jeff-P** [MikeKovarik/exifr#26]
I found this library in the exif js github. Do you have any examples on how to use this with dropzone as exif js did? Looks like a really great library

**Comment by MikeKovarik** [comment]
Hello, thanks. There are a few examples in the [examples folder](https://github.com/MikeKovarik/exifr/tree/master/examples) and there's also [benchmark/gps-dnd.html](https://github.com/MikeKovarik/exifr/blob/master/benchmark/gps-dnd.html) which serves as a benchmark for processing large ammount of photos (thus the benchmark/ instead of examples/ folder) but there you can see the library used with drag and drop
