### ISSUE TITLE
.parse() Not Accepting Arguments

### ISSUE THREAD

**Issue by tedstark** [MikeKovarik/exifr#48]
I'm trying to use exifr in a small browser camera app for a concept demo.  However, when I attempt to use `exifr.parse(file)` per your READ.ME, VS Code throws an error complaining about arguments and there's an error in the console related to `getUint16()`.

Alternatively, when I try to use the `exifr.read(file).then(exifr.parse)` chain, VS Code doesn't complain, but again an console error comes up for the setup() function in the exifr code.

Looking at the latest exifr code, I see that parse() doesn't appear to accept arguments, so I'm not sure if the READ.ME is way out of date, or if I'm just completely missing something in the code...or my code..

Speaking of code, my app is here: https://github.com/tedstark/AngularCameraWebApp.  Screenshots of my errors are included in the repo and the lines in question are in the camera-app.service.ts file, lines 83-87

Thanks!

**Comment by MikeKovarik** [comment]
Hello, thanks for using exifr.

I see what the problem is.
The library exports a few high level functions that internally create instance of Exifr class, read file and then parse. You instead accidentally created the Exifr instance, skipped file reading and went straight for parsing.

You can either add exifr.read() and keep using the low level api (Exifr class instance) ...
```js
import {Exifr} from 'exifr'
imageCapture.takePhoto().then(async blob => {
	const newFile = new File([blob], "photo.jpg", { type: "image/jpeg" })
	let exifr = new Exifr
	await exifr.read(newFile)
	let output = await exifr.parse() // parse method does not accept any arguments
	console.log('Camera:', output.Make, output.Model)
})
```

... or just use the parse function of the high level api.
```js
import exifr from 'exifr'
imageCapture.takePhoto().then(async blob => {
	const newFile = new File([blob], "photo.jpg", { type: "image/jpeg" })
	exifr.parse(newFile).then(output => console.log('Camera:', output.Make, output.Model))
})
```

I know it can be confusing, I will consider improving this.
BTW: you may be asking, why expose Exifr class at all? It's useful when you want to both parse exif and also extract thumbnail.

Happy parsing

**Comment by tedstark** [comment]
Mike, 
Thanks so for the clarifications and examples.  Your help was exactly what I needed. I think I was missing the significance of the difference between low level and high level APIs. But that's likely due to my own inexperience than anything missing from your documentation.  Thank you for the help again!
