### ISSUE TITLE
.PSD and .PDF

### ISSUE THREAD

**Issue by skavan** [MikeKovarik/exifr#49]
Hi,

Adobe Photoshop (and other software programs) store metadata in XMP format. But I can't get exifr to accept PSD and PDF files to scan for the data. Any ideas -- or is this not possible? Great Library for all other formats!

Thanks.

**Comment by MikeKovarik** [comment]
Hello, thanks for liking exifr. Unfortunately neither of these formats are supported. I believe it would be possible with at least psd, since it can also include ICC and IPTC if I'm not wrong. But right now, I unfortunately don't have enough time to promise the feature. Though I'd gladly accept and assist with PRs.
