### ISSUE TITLE
Region support

### ISSUE THREAD

**Issue by bpatrik** [MikeKovarik/exifr#59]
Hi,

I'm looking for a "one exif reader above all" for my home project https://github.com/bpatrik/pigallery2 ([currently I'm using 4](https://github.com/bpatrik/pigallery2/issues/212#issuecomment-808884895)). Exifr looks really promising. 

After a quick testing, I see that unfortunately it does not support regions:
![kép](https://user-images.githubusercontent.com/7512182/112898768-8ba7bf80-90e1-11eb-91d3-675d7d7508b1.png)
(From: http://metapicz.com/)

It recoginses the Area, but does not attach the Area label (i.e.: the type of the area, e.g.: face and the name of the area eg.: Name of the person) to it: 
![kép](https://user-images.githubusercontent.com/7512182/112899078-f35e0a80-90e1-11eb-91b4-5586da713a50.png)

This feature is needed to get multiple, tagged people (faces) from the photo.

Is there any plan adding this feature?

Thank you!

If helps, here is how I get this value using `exifreader`: https://github.com/bpatrik/pigallery2/blob/36ecbcbd3d5d3e659ddf20add456982dcb960d3d/src/backend/model/threading/MetadataLoader.ts#L221-L270

I used this photo for testing: https://github.com/bpatrik/pigallery2/blob/master/demo/images/IMG_6253.jpg

**Comment by MikeKovarik** [comment]
Hello.
First of all, I'm so sorry for responding with such a delay. I usually don't have enough free time. But then the last month has been insane and grotesque. One of the reasons was packing and moving to a new flat. And I wish that would've been the only thing that happened :D.

I finally managed to secure an hour or two to myself last night and took a look at it. Luckily the bug was easy to spot and fix. The problem turned out to be the format of XMP. Specifically: nested `rdf:Description` which I expected could only be used once as a container of the whole document. I'm not sure the XMP data in your photo is valid. I guess it must be, I just haven't come across this case during my research.

Anyway. It is fixed in the master right now and I'll try to release it sometime today or tomorrow.

**Comment by bpatrik** [comment]
Thank you for your work!

I'm using Adobe Lightroom to set these tags. I do not know if that is valid, but def. a well known app :)

**Comment by MikeKovarik** [comment]
Hello @bpatrik. I'm happy to announce v7.0.0. It fixes a bug in XMP which caused the missing region data. 
The parsed output is different so it's a breaking change, hence the major version.
I'd be happy if you could try it out. Let me know if there's anything else.
And thanks for pointing this out. This shed a light on a whole lot of other potential hard-to-find problems.
