### ISSUE TITLE
AVIF support?

### ISSUE THREAD

**Issue by StigNygaard** [MikeKovarik/exifr#60]
Hi Mike

First of all, if your repository had a Discussion forum, I would probably start by posting a question there, before eventually submitting this "issue". But I hope this is okay:-)

I'm the author of [_xIFr_, an EXIF-reader browser extension for the desktop Firefox browser](https://github.com/StigNygaard/xIFr) (In principle coded as a cross-browser extension, but currently with limited functionality in other browsers). The (almost) name-clash with your library is a coincidence. I didn't discover your library until much after naming and launching xIFr.

Currently parsing in xIFr is based on code forked from other older EXIF-viewer Firefox extensions (wxIF and FxIF - and you probably see where I got the name inspiration from). It works fine enough, but is JPG-only. I would very much like to support more image-formats in future versions of xIFr, especially AVIF which I see a great future for on the web. Chrome/Chromium have supported AVIF for some time, Mozilla is expected to [support it officially from Firefox version 90](https://bugzilla.mozilla.org/show_bug.cgi?id=1443863) (ETA: June 29th). And Microsoft, which has chosen _not_ to use the build-in AVIF/AV1 support in chromium, are [also working on it for Edge](https://twitter.com/ericlaw/status/1343797396422144001).

I don't know much about file-formats. You don't mention AVIF support, but I'm told AVIF is based on "HEIC containers", so maybe it is not such a big step to add support for AVIF too (I naively asks/suggests) ? 

A great bonus of your library is that it seems I would be able to read the "true" ICC profile. Currently xIFr displays color space information found in EXIF/XMP, but that is often out of sync with the actually used profile.

/Stig

**Comment by MikeKovarik** [comment]
Hello, thanks for reaching out.

Yeah, place for a discussion beside github is a good idea. I used to use Gitter or Discord but no one came :D so github is fine by me for now.

Wow, I didn't realize AVIF's support in browsers is just around the corner. I'm aware of the format, but didn't get my hands on it since it's not so widespread yet. Of course I would ideally want to support all formats, but it always takes a lot of time.
Luckily, like you said. AVIF uses ISO/BMFF structure. I took a quick look at repurposing the existing heic parser and it worked.

There's something strange going on with ICC though. It looks like a lot of AVIF files contain some 19 bytes of ICC data. It's actually not full ICC profile and no other tools (at least the ones i use for crosstesting) seem to pick on it. It results in a silent error for now. I will have to investigate it in the future. Perhaps I'll need to skip these 19 bytes as it appears to be a pattern with avifs.

Anyway. Proper ICC data is parsed just fine, like with any other file format.
I wanted to enable the AVIF format ASAP, so I'll be releasing 6.3.0 in a minute. I'd be happpy if you end up using exifr and hope it serves you well.
Feel free to come back with any bugs or other suggestions.
Mike

**Comment by StigNygaard** [comment]
Cool Mike. Looks forward to experiment with it, and hopefully I can find time/energy to update xIFr with it. 
Btw, from discussions on related Firefox issues in bugzilla, I know there's a number of invalid (by specs) AVIF files out there, even though they might display in Chrome browser. There should be some file validation service somewhere, but don't have the link right now.
Also of interest might be this Photoshop AVIF-plugin recently released which seems to work, though I haven't tried validating the AVIF files it creates: https://github.com/0xC0000054/avif-format
